#!/usr/bin/env node
/**
 * Publishes the opentrms-videogen output into the Learn section of the docs.
 * Run via `npm run sync-videos` after generating or regenerating a video.
 *
 * Everything under docs/learn/ and static/learn/assets/ is derived from the videogen
 * `out/` directory and is rewritten wholesale on every run. Never hand-edit a
 * page there: change the scenario YAML and regenerate, or the edit is lost on
 * the next sync. Hand-written Learn pages belong outside docs/learn/.
 *
 * Like sync-from-source.mjs, this never throws on missing input: it warns and
 * carries on, so a half-generated out/ directory cannot break the build.
 *
 * Where the video comes from, in order:
 *   1. A YouTube id in scripts/learn-videos.mjs — the published path.
 *   2. LEARN_VIDEO_BASE_URL, if the videos are ever self-hosted instead.
 *   3. The local .mp4, copied into static/learn/assets/ so a walkthrough is
 *      previewable before it is uploaded. Gitignored — see .gitignore.
 *
 * Env overrides:
 *   OPENTRMS_VIDEOGEN     - path to the videogen repo (default: ~/ideas/opentrms-videogen)
 *   LEARN_VIDEO_BASE_URL  - base URL for self-hosted .mp4 files (see 2 above).
 */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

import {SECTIONS, UNLISTED_SECTION} from './learn-sections.mjs';
import {YOUTUBE_IDS} from './learn-videos.mjs';

const VIDEOGEN = process.env.OPENTRMS_VIDEOGEN || path.join(os.homedir(), 'ideas/opentrms-videogen');
const OUT_DIR = path.join(VIDEOGEN, 'out');
const VIDEO_BASE_URL = (process.env.LEARN_VIDEO_BASE_URL || '').replace(/\/+$/, '');

const REPO_ROOT = path.join(import.meta.dirname, '..');
const DOCS_LEARN = path.join(REPO_ROOT, 'docs/learn');
// Assets live under /learn/assets/ so they can never collide with a section
// route: a section directory named after a walkthrough slug would otherwise
// shadow, or be shadowed by, that walkthrough's screenshots.
const STATIC_LEARN = path.join(REPO_ROOT, 'static/learn/assets');

let warnings = 0;

function warn(msg) {
  warnings += 1;
  console.warn(`[sync-videos] WARN: ${msg}`);
}

function info(msg) {
  console.log(`[sync-videos] ${msg}`);
}

/**
 * Accepts either a bare video id or any YouTube URL — a share link is what you
 * have in hand right after an upload, so requiring the id invites silent typos.
 */
function youtubeId(value) {
  const raw = String(value ?? '').trim();
  if (!raw) return null;
  if (!raw.includes('/')) return raw;
  const match = raw.match(/(?:youtu\.be\/|[?&]v=|\/embed\/|\/shorts\/)([A-Za-z0-9_-]{6,})/);
  return match ? match[1] : null;
}

/** MDX reads `{` and `<` as expression syntax; generated prose must not. */
function escapeMdx(text) {
  return text.replace(/[{}]/g, (ch) => `&#${ch.charCodeAt(0)};`).replace(/</g, '&lt;');
}

function yamlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

// ── Reading the generator's output ─────────────────────────────────────────

/**
 * The generated markdown is predictable: an H1, a description paragraph, a
 * blockquote naming the video and captions, a `---`, then numbered steps each
 * followed by a screenshot. We take the metadata off the top and keep the
 * steps as the body.
 */
function parseWalkthrough(slug, markdown) {
  const lines = markdown.split('\n');

  const titleIdx = lines.findIndex((line) => line.startsWith('# '));
  if (titleIdx === -1) {
    warn(`${slug}.md has no H1 title; skipping.`);
    return null;
  }
  const title = lines[titleIdx].slice(2).trim();

  const description = lines
    .slice(titleIdx + 1)
    .find((line) => line.trim() && !line.startsWith('>') && !line.startsWith('#'))
    ?.trim() ?? '';

  const duration = markdown.match(/\*\*Video:\*\*.*·\s*([0-9]+m\s*[0-9]+s)/)?.[1] ?? null;

  // The body starts after the `---` that closes the metadata block.
  const ruleIdx = lines.findIndex((line, i) => i > titleIdx && line.trim() === '---');
  const body = ruleIdx === -1 ? lines.slice(titleIdx + 1) : lines.slice(ruleIdx + 1);

  return {title, description, duration, body};
}

/** Rewrites `./<slug>-assets/step-01.png` to the published static path. */
function rewriteBody(slug, body) {
  const kept = [];
  for (const line of body) {
    // Drop the generator's own footer; this file says the same thing better.
    if (line.includes('Generated by `opentrms-videogen`')) continue;

    const image = line.match(/^!\[(.*?)\]\(\.\/.*?\/(step-\d+\.png)\)\s*$/);
    if (image) {
      kept.push(`![${escapeMdx(image[1])}](/learn/assets/${slug}/${image[2]})`);
      continue;
    }
    if (line.startsWith('#') || !line.trim()) {
      kept.push(line);
      continue;
    }
    kept.push(escapeMdx(line));
  }

  // Collapse the trailing blank lines and stray rule the footer left behind.
  while (kept.length && (!kept[kept.length - 1].trim() || kept[kept.length - 1].trim() === '---')) {
    kept.pop();
  }
  return kept.join('\n');
}

/**
 * SRT to WebVTT: the HTML5 <track> element does not accept SRT. The formats
 * differ only in a header and the decimal separator of the timestamps.
 */
function srtToVtt(srt) {
  const body = srt
    .replace(/\r\n/g, '\n')
    .replace(/^﻿/, '')
    .replace(/(\d{2}:\d{2}:\d{2}),(\d{3})/g, '$1.$2');
  return `WEBVTT\n\n${body.trim()}\n`;
}

/** The spoken narration as paragraphs, so it is searchable as page text. */
function srtToTranscript(srt) {
  return srt
    .replace(/\r\n/g, '\n')
    .trim()
    .split(/\n\s*\n/)
    .map((cue) => cue.split('\n').filter((line) => !/^\d+$/.test(line) && !line.includes('-->')))
    .filter((cue) => cue.length)
    .map((cue) => escapeMdx(cue.join(' ').trim()));
}

// ── Writing the docs tree ──────────────────────────────────────────────────

function copyIfChanged(src, dest) {
  try {
    const srcStat = fs.statSync(src);
    const destStat = fs.existsSync(dest) ? fs.statSync(dest) : null;
    if (destStat && destStat.size === srcStat.size && destStat.mtimeMs >= srcStat.mtimeMs) {
      return true;
    }
    fs.mkdirSync(path.dirname(dest), {recursive: true});
    fs.copyFileSync(src, dest);
    return true;
  } catch (err) {
    warn(`Could not copy ${src} (${err.code ?? err.message}).`);
    return false;
  }
}

function copyScreenshots(slug, assetsDir, destDir) {
  let entries;
  try {
    entries = fs.readdirSync(assetsDir).filter((name) => name.endsWith('.png')).sort();
  } catch {
    warn(`${slug}: no assets directory at ${assetsDir}; the page will have no screenshots.`);
    return [];
  }
  const copied = [];
  for (const name of entries) {
    if (copyIfChanged(path.join(assetsDir, name), path.join(destDir, name))) {
      copied.push(name);
    }
  }
  return copied;
}

function writePage({slug, section, position, meta, videoUrl, youtubeId, captionsUrl, poster, transcript}) {
  const frontmatter = [
    '---',
    `title: ${yamlString(meta.title)}`,
    meta.description ? `description: ${yamlString(meta.description)}` : null,
    `sidebar_position: ${position}`,
    '---',
  ].filter(Boolean).join('\n');

  const props = [
    youtubeId ? `  youtube=${JSON.stringify(youtubeId)}` : null,
    videoUrl ? `  video=${JSON.stringify(videoUrl)}` : null,
    captionsUrl && !youtubeId ? `  captions=${JSON.stringify(captionsUrl)}` : null,
    poster ? `  poster=${JSON.stringify(poster)}` : null,
    meta.duration ? `  duration=${JSON.stringify(meta.duration)}` : null,
  ].filter(Boolean).join('\n');

  const transcriptBlock = transcript.length
    ? `\n${transcript.map((para) => para).join('\n\n')}\n`
    : '\n_No transcript was generated for this walkthrough._\n';

  const page = `${frontmatter}

{/* Generated from opentrms-videogen by \`npm run sync-videos\`. Do not edit:
    change scenarios/${slug}.yaml and regenerate, or this file overwrites you. */}

import Walkthrough from '@site/src/components/Walkthrough';

${meta.description ? `${escapeMdx(meta.description)}\n` : ''}
<Walkthrough
${props}
>
${transcriptBlock}
</Walkthrough>

${rewriteBody(slug, meta.body)}
`;

  const dest = path.join(DOCS_LEARN, section.dir, `${slug}.mdx`);
  fs.mkdirSync(path.dirname(dest), {recursive: true});
  fs.writeFileSync(dest, page, 'utf8');
  return dest;
}

function writeCategory(section, position) {
  const dest = path.join(DOCS_LEARN, section.dir, '_category_.json');
  fs.mkdirSync(path.dirname(dest), {recursive: true});
  fs.writeFileSync(dest, `${JSON.stringify({
    label: section.label,
    position,
    collapsible: false,
    link: {type: 'generated-index', description: section.description},
  }, null, 2)}\n`, 'utf8');
}

// ── Main ───────────────────────────────────────────────────────────────────

function main() {
  if (!fs.existsSync(OUT_DIR)) {
    warn(`No videogen output at ${OUT_DIR}. Set OPENTRMS_VIDEOGEN or run the generator first.`);
    warn('Leaving docs/learn untouched.');
    process.exit(0);
  }

  const slugs = fs.readdirSync(OUT_DIR)
    .filter((name) => name.endsWith('.md'))
    .map((name) => name.slice(0, -3))
    .sort();

  if (!slugs.length) {
    warn(`${OUT_DIR} holds no walkthrough markdown. Leaving docs/learn untouched.`);
    process.exit(0);
  }

  // Regenerate wholesale so a deleted or renamed scenario cannot leave a
  // stale page behind. Only ever removes directories this script wrote.
  fs.rmSync(DOCS_LEARN, {recursive: true, force: true});
  fs.mkdirSync(DOCS_LEARN, {recursive: true});

  const claimed = new Set(SECTIONS.flatMap((section) => section.slugs));
  const unlisted = slugs.filter((slug) => !claimed.has(slug));
  const sections = unlisted.length
    ? [...SECTIONS, {...UNLISTED_SECTION, slugs: unlisted}]
    : SECTIONS;

  for (const slug of unlisted) {
    warn(`${slug} is in no section — publishing under "${UNLISTED_SECTION.label}". `
      + 'Add it to scripts/learn-sections.mjs.');
  }

  let pages = 0;
  const unmapped = [];

  sections.forEach((section, sectionIndex) => {
    const present = section.slugs.filter((slug) => {
      if (slugs.includes(slug)) return true;
      warn(`${section.label}: no generated walkthrough for "${slug}" — skipping it.`);
      return false;
    });
    if (!present.length) return;

    writeCategory(section, sectionIndex + 1);

    present.forEach((slug, slugIndex) => {
      const markdown = fs.readFileSync(path.join(OUT_DIR, `${slug}.md`), 'utf8');
      const meta = parseWalkthrough(slug, markdown);
      if (!meta) return;

      const staticDir = path.join(STATIC_LEARN, slug);
      const screenshots = copyScreenshots(slug, path.join(OUT_DIR, `${slug}-assets`), staticDir);

      // Captions: convert alongside the screenshots so the <track> resolves.
      let captionsUrl = null;
      let transcript = [];
      const srtPath = path.join(OUT_DIR, `${slug}.srt`);
      if (fs.existsSync(srtPath)) {
        const srt = fs.readFileSync(srtPath, 'utf8');
        fs.mkdirSync(staticDir, {recursive: true});
        fs.writeFileSync(path.join(staticDir, `${slug}.vtt`), srtToVtt(srt), 'utf8');
        captionsUrl = `/learn/assets/${slug}/${slug}.vtt`;
        transcript = srtToTranscript(srt);
      } else {
        warn(`${slug}: no .srt — the page ships without captions or a transcript.`);
      }

      // Video: hosted externally when a base URL is configured, copied in for
      // local preview otherwise. Committing ~5 MB per walkthrough to git would
      // add a new copy to history on every regeneration.
      let videoUrl = null;
      const mapped = YOUTUBE_IDS[slug] ?? null;
      const videoId = youtubeId(mapped);
      if (mapped && !videoId) {
        warn(`${slug}: could not read a video id out of "${mapped}" — falling back to local video.`);
      }
      const mp4Path = path.join(OUT_DIR, `${slug}.mp4`);
      if (videoId) {
        // Published: embed it, and don't copy 5 MB nobody will load.
      } else if (VIDEO_BASE_URL) {
        videoUrl = `${VIDEO_BASE_URL}/${slug}.mp4`;
      } else if (fs.existsSync(mp4Path)) {
        copyIfChanged(mp4Path, path.join(staticDir, `${slug}.mp4`));
        videoUrl = `/learn/assets/${slug}/${slug}.mp4`;
        unmapped.push(slug);
      } else {
        warn(`${slug}: no .mp4 and no YouTube id — the page ships as screenshots and text only.`);
      }

      writePage({
        slug,
        section,
        position: slugIndex + 1,
        meta,
        videoUrl,
        youtubeId: videoId,
        captionsUrl,
        poster: screenshots.length ? `/learn/assets/${slug}/${screenshots[0]}` : null,
        transcript,
      });
      pages += 1;
      info(`${section.dir}/${slug} — ${screenshots.length} screenshots`
        + `${captionsUrl ? ', captions' : ''}`
        + `${videoId ? `, youtube:${videoId}` : videoUrl ? ', local video' : ''}`);
    });
  });

  info(`Wrote ${pages} walkthrough${pages === 1 ? '' : 's'} to docs/learn/.`);
  if (unmapped.length) {
    warn(`${unmapped.length} walkthrough${unmapped.length === 1 ? ' has' : 's have'} no YouTube id `
      + `and will not play once deployed: ${unmapped.join(', ')}.`);
    warn('Upload them and add their ids to scripts/learn-videos.mjs.');
  }
  if (warnings) {
    info(`${warnings} warning${warnings === 1 ? '' : 's'} above.`);
  }
}

main();
